---
version: 2

updates:
  - package-ecosystem: github-actions
    cooldown:
      default-days: 7
    directory: /
    target-branch: main
    rebase-strategy: auto
    schedule:
      interval: monthly
    assignees:
      - georglauterbach
    labels:
      - area/ci
      - kind/update
      - priority/low
      - meta/needs-triage
